fix(inputs.procstat) Collect swap via /proc//smaps
aws/telegraf pull request #159
Opened 2024-09-22 18:59 UTC by Paramadon

### Required for all PRs:

- [ x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

Currently proc.MemoryInfo() claims to collect rss, vms, as well as swap, data, stack, and locked information. This functions reads from /proc/$PID/statm. However the gopsutil function only returns two values, rss and vsm, the first and second value from that file. Additionally, the man page for proc says that instead of statm users should look to smaps or smaps_rollup:

If accurate values are required, use /proc/pid/smaps or /proc/pid/smaps_rollup instead
This change will keep rss and vms from the /proc/$PID/statm file and introduce a call to /proc/$PID/smaps

size: total size
pss: process's proportional share of this mapping
shared_clean/shared_dirty: the number of clean and dirty shared pages in the mapping
private_clean/private_dirty: the number of clean and dirty private pages in the mapping
referenced: the amount of memory currently marked as referenced or accessed
anonymous: the amount of memory that does not belong to any file
swap: how much would-be-anonymous memory is also used, but out on swap
As the previous values were always zero, users should not have any expectations on the data, stack, or locked fields. This does mean users can now get the swap field as well as the new fields.

fixes: https://github.com/influxdata/telegraf/issues/8557
Similar pr to this fix: https://github.com/influxdata/telegraf/pull/13779

2024-09-26 19:18 UTC, lisguo commented on plugins/inputs/procstat/procstat.go
> -		fields[prefix+"memory_swap"] = mem.Swap
any reason why we removed these?

2024-09-26 19:21 UTC, Paramadon commented on plugins/inputs/procstat/procstat.go
> -		fields[prefix+"memory_swap"] = mem.Swap
it is part of the cherry pick, this uses gopsutil which doesn't return any real values to  mem.Swap, mem.Data, mem.Stack, mem.Locked. They are always zero. Which is where collectMemmap comes in and it instead uses smap to get the memory_swap info

2024-09-26 19:32 UTC, lisguo approved these changes

2024-09-26 21:38 UTC, jefchien reviewed
It doesn't look like we cherry-picked the commit and instead pulled in some of the changes. If that's the case, then we don't need to be 1:1 with those changes.

2024-09-26 21:38 UTC, jefchien commented on go.mod
> +toolchain go1.22.5
These do not need to be changed.

2024-09-26 21:38 UTC, jefchien commented on plugins/inputs/procstat/process.go
> +	"github.com/influxdata/telegraf/metric"
nit: Fix the imports.

2024-09-26 21:38 UTC, jefchien commented on plugins/inputs/procstat/process.go
> +	Metric(string, *collectionConfig) telegraf.Metric
What is this function for? I don't see it being called.

2024-09-26 21:38 UTC, jefchien commented on plugins/inputs/procstat/procstat.go
> -		fields[prefix+"memory_swap"] = mem.Swap
While the metrics were always 0, they still existed. Now with this part removed, those metrics are no longer going to be emitted. Sounds like a regression to me.

2024-09-26 21:38 UTC, jefchien commented on plugins/inputs/procstat/procstat.go
> +		case "cpu", "limits", "memory", "mmap": //"cpu", "limits", "memory" not needed (might be useful for the future)
Don't include properties that aren't valid.

2024-09-26 21:38 UTC, jefchien commented on plugins/inputs/procstat/procstat_test.go
> +	"github.com/influxdata/telegraf"
nit: Fix import order/grouping.

2024-09-26 21:38 UTC, jefchien commented on plugins/inputs/procstat/memmap.go
> +func collectMemmap(proc Process, prefix string, fields map[string]any) {
Add a comment with the commit that we pulled this from.

2024-09-27 17:18 UTC, jefchien requested changes

2024-09-27 17:18 UTC, jefchien commented on plugins/inputs/procstat/process.go
> +func (p *Proc) Metric(prefix string, cfg *collectionConfig) telegraf.Metric {
The `Metric` function was removed from the interface, but it's still being added here. Is this ever used?

2024-09-27 17:18 UTC, jefchien commented on plugins/inputs/procstat/procstat_test.go
> +func (p *testProc) Metric(prefix string, cfg *collectionConfig) telegraf.Metric {
Same here.

2024-09-27 17:30 UTC, Paramadon commented on plugins/inputs/procstat/process.go
> +func (p *Proc) Metric(prefix string, cfg *collectionConfig) telegraf.Metric {
It is not being used, it was part of the pr that we are pulling this from, but since we are only pulling in memory_swap metric changes this is not needed.

2024-09-27 17:40 UTC, jefchien submitted a review, later dismissed

2024-09-27 17:40 UTC, jefchien commented on plugins/inputs/procstat/procstat.go
> +	collectMemmap(proc, prefix, fields)
This still needs to be gated by the feature flag. That's why we're pulling in the `Properties` field.

2024-09-27 18:05 UTC, jefchien commented on plugins/inputs/procstat/procstat.go
> +			Properties:    []string{"mmap"},
Why are we pre-defining the Properties? Shouldn't this be provided through the configuration?

2024-09-27 18:24 UTC, Paramadon commented on plugins/inputs/procstat/procstat.go
> +			Properties:    []string{"mmap"},
it exists in this pull: https://github.com/srebhan/telegraf/blob/ae17a696b5b238deeb469b48da683ccb63c277e8/plugins/inputs/procstat/procstat.go#L646

2024-09-27 22:39 UTC, musa-asad approved these changes

2024-09-30 14:09 UTC, jefchien commented on plugins/inputs/procstat/procstat_test.go
> +		Properties:      []string{"mmap"},
None of these unit tests actually test the changes.

2024-09-30 18:03 UTC, jefchien commented on plugins/inputs/procstat/procstat_test.go
> +			return &testProc{
The test should populate the `process.MemoryMapsStat` returned by `MemoryMap` so we can verify that if the function returns a value, it will get picked up.

2024-09-30 18:47 UTC, Paramadon commented on plugins/inputs/procstat/procstat_test.go
> +			return &testProc{
done

2024-10-01 14:48 UTC, jefchien approved these changes

2024-10-01 15:04 UTC, merged